=begin
Pentagonal numbers are generated by the formula, P_(n)=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_(4) + P_(7) = 22 + 70 = 92 = P_(8). However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_(j) and P_(k),
 for which their sum and difference is pentagonal and D = |P_(k) − P_(j)| is minimised; what is the value of D?
=end

require_relative 'lib'

def P(n)
  n*(3*n-1)/2
end

class Integer
  def pentagonal?
    self > 0 and Math.sqrt(1+24*self) % 6 == 5 # just doing basic maths on n(3n-1)/2 == self
  end
end

pentagonals = (1..3_000).map { |n| P(n) }.reverse

p pentagonals.all? { |p| p.pentagonal? }

p pairs = pentagonals.combination(2).select { |pj, pk|
  (pj + pk).pentagonal? and (pj - pk).pentagonal?
} # => [[7042750, 1560090]]

p pairs.map { |pj, pk| pj-pk }.min # => 5482660, 6s
