=begin
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	T_(n)=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	P_(n)=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	H_(n)=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T_(285) = P_(165) = H_(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.  
=end

class NumberSet
  attr_reader :last
  def initialize(&block)
    @formula = block
    @i = 0
    find_next
  end
  
  def find_next
    @i += 1
    @last = @formula[@i]
  end
end

triangle = NumberSet.new { |n| n*(n+1)/2 }
pentagonal = NumberSet.new { |n| n*(3*n-1)/2 }
hexagonal = NumberSet.new { |n| n*(2*n-1) }
sets = [triangle, pentagonal, hexagonal]

p (40755+1..100_000_000).each { |n|
  p n if n % 10**6 == 0
  sets.each { |nset|
    nset.find_next until nset.last >= n
  }
  break(n) if sets.all? { |nset| nset.last == n }
}
p sets
